// <auto-generated />
using LibraryApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryAppContext))]
    partial class LibraryAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        });
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DemoId = 1,
                            Name = "Lev Tolstoy"
                        });
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfPublication")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DemoId = 1,
                            Description = "Desctiption Test",
                            ISBN = "979-8589744965",
                            Title = "War and Peace, Volume 1",
                            YearOfPublication = 2021
                        },
                        new
                        {
                            Id = 2,
                            DemoId = 2,
                            Description = "Desctiption Test",
                            ISBN = "979-8589744945",
                            Title = "Book For Demo #1",
                            YearOfPublication = 2023
                        },
                        new
                        {
                            Id = 3,
                            DemoId = 3,
                            Description = "Desctiption Test",
                            ISBN = "979-8589744955",
                            Title = "Book For Demo #2",
                            YearOfPublication = 2023
                        });
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.BookInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("DemoId");

                    b.ToTable("BookInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            DemoId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            DemoId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            DemoId = 1
                        });
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.DemoInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DemoInfo");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.Patron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DemoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoId")
                        .IsUnique();

                    b.ToTable("Patrons");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("LibraryApp.Core.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Core.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.Author", b =>
                {
                    b.HasOne("LibraryApp.Core.Entities.DemoInfo", "Demo")
                        .WithMany("Authors")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demo");
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.Book", b =>
                {
                    b.HasOne("LibraryApp.Core.Entities.DemoInfo", "Demo")
                        .WithMany("Books")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demo");
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.BookInstance", b =>
                {
                    b.HasOne("LibraryApp.Core.Entities.Book", "Book")
                        .WithMany("bookInstances")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Core.Entities.DemoInfo", "Demo")
                        .WithMany()
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Demo");
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.Patron", b =>
                {
                    b.HasOne("LibraryApp.Core.Entities.DemoInfo", "Demo")
                        .WithOne("Patron")
                        .HasForeignKey("LibraryApp.Core.Entities.Patron", "DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Demo");
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.Book", b =>
                {
                    b.Navigation("bookInstances");
                });

            modelBuilder.Entity("LibraryApp.Core.Entities.DemoInfo", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Books");

                    b.Navigation("Patron")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
